# Generated by Django 4.1 on 2023-05-15 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IndustryCrossPrimary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Compensation", models.FloatField(verbose_name="Compensation%")),
                (
                    "OperatingSurplus",
                    models.FloatField(verbose_name="Operating Surplus%"),
                ),
                (
                    "ConsumptionOfFixedCapital",
                    models.FloatField(verbose_name="Consumption of Fixed Capital%"),
                ),
                ("NetTaxes", models.FloatField(verbose_name="Net taxes%")),
                ("Imports", models.FloatField(verbose_name="Imports%")),
                ("Total", models.FloatField(verbose_name="Total%")),
            ],
            options={
                "verbose_name": "Primary & industry cross-tablated statistics",
                "verbose_name_plural": "Primary & industry cross-tablated statistics",
            },
        ),
        migrations.CreateModel(
            name="SectorName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Sector")),
            ],
            options={
                "verbose_name": "Sector",
                "verbose_name_plural": "Sector",
            },
        ),
        migrations.CreateModel(
            name="Year",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Year")),
            ],
            options={
                "verbose_name": "Year",
                "verbose_name_plural": "Year",
            },
        ),
        migrations.CreateModel(
            name="StageShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FarmGate", models.FloatField(default=0, verbose_name="Farm Gate")),
                ("TransGate", models.FloatField(default=0, verbose_name="Trans Gate")),
                (
                    "ProcessGate",
                    models.FloatField(default=0, verbose_name="Process Gate"),
                ),
                ("TradeGate", models.FloatField(default=0, verbose_name="Trade Gate")),
                (
                    "sectorName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.sectorname",
                        verbose_name="Sector",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.year",
                        verbose_name="Year",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stage Share",
                "verbose_name_plural": "Stage Share",
            },
        ),
        migrations.CreateModel(
            name="Primary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Compensation", models.FloatField(verbose_name="Compensation")),
                (
                    "OperatingSurplus",
                    models.FloatField(verbose_name="Operating Surplus"),
                ),
                (
                    "ConsumptionOfFixedCapital",
                    models.FloatField(verbose_name="Consumption of Fixed Capital"),
                ),
                ("NetTaxes", models.FloatField(verbose_name="Net taxes")),
                ("Imports", models.FloatField(verbose_name="Imports")),
                (
                    "sectorName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.sectorname",
                        verbose_name="Sector",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.year",
                        verbose_name="Year",
                    ),
                ),
            ],
            options={
                "verbose_name": "Primary Bill",
                "verbose_name_plural": "Primary Bill",
            },
        ),
        migrations.CreateModel(
            name="Marketing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FarmShare", models.FloatField(verbose_name="Farm Share")),
                ("MarketingShare", models.FloatField(verbose_name="Marketing Share")),
                (
                    "sectorName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.sectorname",
                        verbose_name="Sector",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.year",
                        verbose_name="Year",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marketing Bill",
                "verbose_name_plural": "Marketing Bill",
            },
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agribusiness", models.FloatField(verbose_name="Agribusiness")),
                ("FarmProduction", models.FloatField(verbose_name="Farm Production")),
                ("FoodProcess", models.FloatField(verbose_name="Food Process")),
                ("Packaging", models.FloatField(verbose_name="Packaging")),
                ("Transportation", models.FloatField(verbose_name="Transportation")),
                ("WholesaleTrade", models.FloatField(verbose_name="Wholesale trade")),
                ("RetailTrade", models.FloatField(verbose_name="Retail trade")),
                ("FoodService", models.FloatField(verbose_name="Food service")),
                ("Energy", models.FloatField(verbose_name="Energy")),
                (
                    "FinanceInsurance",
                    models.FloatField(verbose_name="Finance and insurance"),
                ),
                ("Advertising", models.FloatField(verbose_name="Advertising")),
                (
                    "sectorName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.sectorname",
                        verbose_name="Sector",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.year",
                        verbose_name="Year",
                    ),
                ),
            ],
            options={
                "verbose_name": "Industry Bill",
                "verbose_name_plural": "Industry Bill",
            },
        ),
    ]
