# Generated by Django 4.1 on 2023-05-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="industry",
            name="Trade",
            field=models.FloatField(default=0, verbose_name="Trade"),
        ),
    ]
