# Generated by Django 4.1 on 2023-05-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_industry_trade"),
    ]

    operations = [
        migrations.AddField(
            model_name="industry",
            name="Accounting",
            field=models.FloatField(default=0, verbose_name="Accounting"),
        ),
        migrations.AddField(
            model_name="primary",
            name="Adjustment",
            field=models.FloatField(default=0, verbose_name="Adjustment"),
        ),
    ]
