# Generated by Django 4.1 on 2023-05-16 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_industry_accounting_primary_adjustment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="industry",
            old_name="sectorName",
            new_name="sector",
        ),
        migrations.RenameField(
            model_name="marketing",
            old_name="sectorName",
            new_name="sector",
        ),
        migrations.RenameField(
            model_name="primary",
            old_name="sectorName",
            new_name="sector",
        ),
        migrations.RenameField(
            model_name="stageshare",
            old_name="sectorName",
            new_name="sector",
        ),
    ]
