# Generated by Django 4.1 on 2023-05-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_rename_accounting_industry_accounting_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="industry",
            name="Advertising",
            field=models.FloatField(default=0, verbose_name="Advertising"),
        ),
        migrations.AlterField(
            model_name="industry",
            name="Agribusiness",
            field=models.FloatField(default=0, verbose_name="Agribusiness"),
        ),
        migrations.AlterField(
            model_name="industry",
            name="Energy",
            field=models.FloatField(default=0, verbose_name="Energy"),
        ),
        migrations.AlterField(
            model_name="industry",
            name="FarmProduction",
            field=models.FloatField(default=0, verbose_name="Farm Production"),
        ),
        migrations.AlterField(
            model_name="industry",
            name="FinanceInsurance",
            field=models.FloatField(default=0, verbose_name="Finance and insurance"),
        ),
        migrations.AlterField(
            model_name="industry",
            name="FoodProcess",
            field=models.FloatField(default=0, verbose_name="Food Process"),
        ),
        migrations.AlterField(
            model_name="industry",
            name="FoodService",
            field=models.FloatField(default=0, verbose_name="Food service"),
        ),
        migrations.AlterField(
            model_name="industry",
            name="Packaging",
            field=models.FloatField(default=0, verbose_name="Packaging"),
        ),
        migrations.AlterField(
            model_name="industry",
            name="RetailTrade",
            field=models.FloatField(default=0, verbose_name="Retail trade"),
        ),
        migrations.AlterField(
            model_name="industry",
            name="Transportation",
            field=models.FloatField(default=0, verbose_name="Transportation"),
        ),
        migrations.AlterField(
            model_name="industry",
            name="WholesaleTrade",
            field=models.FloatField(default=0, verbose_name="Wholesale trade"),
        ),
        migrations.AlterField(
            model_name="marketing",
            name="FarmShare",
            field=models.FloatField(default=0, verbose_name="Farm Share"),
        ),
        migrations.AlterField(
            model_name="marketing",
            name="MarketingShare",
            field=models.FloatField(default=0, verbose_name="Marketing Share"),
        ),
        migrations.AlterField(
            model_name="primary",
            name="Compensation",
            field=models.FloatField(default=0, verbose_name="Compensation"),
        ),
        migrations.AlterField(
            model_name="primary",
            name="ConsumptionOfFixedCapital",
            field=models.FloatField(
                default=0, verbose_name="Consumption of Fixed Capital"
            ),
        ),
        migrations.AlterField(
            model_name="primary",
            name="Imports",
            field=models.FloatField(default=0, verbose_name="Imports"),
        ),
        migrations.AlterField(
            model_name="primary",
            name="NetTaxes",
            field=models.FloatField(default=0, verbose_name="Net taxes"),
        ),
        migrations.AlterField(
            model_name="primary",
            name="OperatingSurplus",
            field=models.FloatField(default=0, verbose_name="Operating Surplus"),
        ),
    ]
