# Generated by Django 4.1 on 2023-11-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_industry_options_alter_marketing_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ['Year'], 'verbose_name': 'Industry Group', 'verbose_name_plural': 'Industry Group'},
        ),
        migrations.AlterModelOptions(
            name='primary',
            options={'ordering': ['Year'], 'verbose_name': 'Primary Factor', 'verbose_name_plural': 'Primary Factor'},
        ),
    ]
